### ISSUE TITLE
hkcam not showing in HomeKit

### ISSUE THREAD

**Issue by Paulg5678** [brutella/hkcam#104]
ok, so this is an odd one, I'm using the preconfigured raspi image and at first I was able to run 'sudo hkcam' and from my phone I could 'add accessory' and it would add, but had no video, I tried 'raspistill -o test.jpg' and got an error and after some more troubleshooting, turns out that the camera module was damaged.

I got a new camera module and now 'raspistill -o test.jpg' works; however, now when I run 'sudo hkcam' I get 2 lines of output, and then it is not visible to add within HomeKit 

Any help or further troubleshooting steps would be appreciated.

**Comment by Paulg5678** [comment]
Issue resolved

**Comment by Jacbey** [comment]
Can you at least tell us how you resolved this instead of just closing it without explaining?

**Comment by switchCTRL** [comment]
> Issue resolved

Can you please describe how you resolved the error? Some others (including me) would find it helpful ;)

**Comment by PvdGulik** [comment]
Yes please, I also do have the same problem

**Comment by servettonga** [comment]
Since OP didn't mention how resolved, I share mine,
deleted `.pairing` files in `/var/lib/hkcam/data`
