### ISSUE TITLE
Restart of HKCam through stop and start command causes video device to be busy

### ISSUE THREAD

**Issue by 0xPr0xy** [brutella/hkcam#106]
I ran `sv stop hkcam` to stop the camera, in order to take a picture with `raspistill -o test.jpg`.
I thought that went fine however then raspistill could not find the camera
```
mmal: mmal_vc_component_enable: failed to enable component: ENOSPC
mmal: camera component couldn't be enabled
mmal: main: Failed to create camera component
mmal: Failed to run camera app. Please check for firmware updates
```
When starting hkcam again with `sv start hkcam` and viewing the logs I got log output 
`connection.go:112: Close connection and remove session`
and `VIDIOC_S_FMT: failed: Device or resource busy3:17.36 bitrate=N/A speed=   1x    s dup=0 drop=2 speed=   1x`

It seems to me stopping hkcam does not actually release the video device completely - which then causes issues.
Issues are gone after reboot though.

**Comment by brutella** [comment]
Please install version [0.1.0](https://github.com/brutella/hkcam/releases/tag/v0.1.0) and try again.

**Comment by brutella** [comment]
Closed due to inactivity.
