### ISSUE TITLE
video0 missing

### ISSUE THREAD

**Issue by Ryan-be** [brutella/hkcam#109]
I have been trying to set hkcam up on a pi zero w. I can ping it fine and ssh in on the same network but it is now showing up in the HomeKit app.  Further investigation shows that the video0 file was missing. Therefore I created it. After which I did chmod 777 on it and did chown root:video (the same as all of the other videoXX files. I have also ensured that the camera is enabled using raspy-config. however the following errors are now showing up in the logs and I am not sure where to go from here. 

2021-02-14_12:45:29.83330 VIDIOC_QUERYCAP: failed: Inappropriate ioctl for device
2021-02-14_12:45:30.88608 /dev/video0: not a v4l2 node
2021-02-14_12:45:30.88827 VIDIOC_QUERYCAP: failed: Inappropriate ioctl for device

**Comment by brutella** [comment]
`/dev/video0` appears automatically if you have a camera module connected to your Pi zero.
