### ISSUE TITLE
what is "pi" user password on pre-configured Raspbian image "-hkcam-v0.0.9-armv6.img.zip" ?

### ISSUE THREAD

**Issue by sciepie** [brutella/hkcam#110]
what is "pi" user password on pre-configured Raspbian image "...-hkcam-v0.0.9-armv6.img.zip" ?

**Comment by sciepie** [comment]
sorry - finally found as default password for standard Raspberian.
but how to configure motion detection alerts?

**Comment by djiwondee** [comment]
@sciepie
> how to configure motion detection alerts?

`hkcam` doesn't provide Apple secure video, which is (afak) a pre-requisite for motion detection alerts in HomeKit
