### ISSUE TITLE
Are "Persistent Snapshots" still supported in the latest Home+ 5 app?

### ISSUE THREAD

**Issue by nanosonde** [brutella/hkcam#113]
@brutella 
Hi!

Do you still support this feature in the recent Home+ 5 app?
Will you still continue to support this in the future?

FYI, I have just opened this ticket: https://github.com/Sunoo/homebridge-camera-ffmpeg/issues/1125

**Comment by brutella** [comment]
> Do you still support this feature in the recent Home+ 5 app?

Yes.

> Will you still continue to support this in the future?

Well, I can't say if it will be supported forever but it still works in version 5.
