### ISSUE TITLE
Rescue mode issue

### ISSUE THREAD

**Issue by BatteryDie** [brutella/hkcam#114]
I tried flashed premade image on 16GB microSD card. It seem boot is not finished. I decided to plug HDMI to find out. It appeared Pi is in rescue mode and root account is locked. Here is photo:

![image](https://user-images.githubusercontent.com/13942195/118290913-f734c900-b4a4-11eb-85ef-b89633a68049.jpeg)

However, I pressed enter button. It caused boot continued and finished but it is still very annoying. I have press enter with USB keyboard every boot.

I tried run `systemctl reboot` and `systemctl default` commands. It do not fix the issue.

I reflashed same 16GB microSD card with latest official Raspberry Pi Os image. There is no issue at all. Now I flashed the premade image on new 16GB microSD card. It still got same issue. I think there is wrong something with the premade image. Maybe it is not compatible with latest firmware of my pi zero w?

**Comment by brutella** [comment]
Try to install the latest version [0.1.0](https://github.com/brutella/hkcam/releases/tag/v0.1.0). Then follow the instructions in the readme which are specific for the latest Raspberry Pi OS release.
