### ISSUE TITLE
Was working with HomeKit directly after setup, now it doesn't

### ISSUE THREAD

**Issue by destinationsound** [brutella/hkcam#117]
I wish I could add loads of detail, but unfortunately, I have no idea what happened. I followed [this tutorial](https://github.com/brutella/hkcam/issues/43) exactly as written. Upon completing it, I was able to attach the camera to my HomeKit app by manually adding the code 001 02 003. 

After a few minutes, the connections stopped and I now can't reconnect it.

Again, I wish I had more info. But as of now any helpful hints to set me in the right direction would be great.

**Comment by PvdGulik** [comment]
Can you still SSH to the Pi? What does the command `journalctl -xefu hkcam` tells you?

**Comment by destinationsound** [comment]
> Can you still SSH to the Pi? What does the command `journalctl -xefu hkcam` tells you?

Sorry for such a delay, put this project on hold. I'm still seeing a weird issue, but can figure out a pattern as it's intermittent. I'll keep an eye on them and see if I can figure out what's happening.

mad far as I can tell the video feed goes unresponsive randomly. And then it comes back after some random time.

**Comment by brutella** [comment]
I've just release version 0.1.0, which should run more reliable than previous versions.
