### ISSUE TITLE
Keine Antwort

### ISSUE THREAD

**Issue by baseship** [brutella/hkcam#12]
Im Anhang die komplette current Datei

[current.txt](https://github.com/brutella/hkcam/files/3233656/current.txt)

**Comment by RaymondMouthaan** [comment]
This might be related to #11 ?

**Comment by baseship** [comment]
yes it's no response, too at restart. First cam is a D-Link Onmia, second is the HKCam.

![IMG_D1E53B2B953B-1](https://user-images.githubusercontent.com/11758521/58578491-38485a00-8249-11e9-80d3-8efe9a3c8ab6.jpeg)

**Comment by brutella** [comment]
Danke für die Log-Dateien.
Es scheint sich um das selbe Problem wit bei Issue #11 zu handeln.
Ich habe bereits einen [möglichen Fix](https://github.com/brutella/hkcam/issues/11#issuecomment-497054087) gepostet.
