### ISSUE TITLE
New Version for the RPi Zero 2 ?

### ISSUE THREAD

**Issue by Loremwriter** [brutella/hkcam#120]
Hello,
will there be a new version for the RPi Zero 2, because the "old" Stretch version wont boot on the zero 2. 
Best regards

**Comment by molly78** [comment]
I’m curious and hopeful about this too.

**Comment by molly78** [comment]
I’ll add to this - same same

**Comment by Zovitar** [comment]
Ahh, thats explains a lot! I was trying to get it to work on my RPi Zero 2 for days not understanding why it didn't work...

Hoping this wil get updated soon!

**Comment by RickWu416** [comment]
I’ll add to this - same same

**Comment by brutella** [comment]
Hi, sorry for not responding sooner.

I've just release version 0.1.0, which is easy to install on a Raspberry Pi running Raspberry Pi OS (Bullseye).
See the instructions in the readme.
