### ISSUE TITLE
Not working in Bullseye

### ISSUE THREAD

**Issue by AzagraMac** [brutella/hkcam#122]
more info: https://www.raspberrypi.com/news/bullseye-camera-system/

**Comment by AzagraMac** [comment]
Link to #274 issue: https://github.com/Hexxeh/rpi-firmware/issues/274#issuecomment-979348468

**Comment by sighmon** [comment]
@AzagraMac It works for me on Bullseye using: `go run cmd/hkcam/main.go -h264_encoder h264_v4l2m2m`

**Comment by Loremwriter** [comment]
> @AzagraMac It works for me on Bullseye using: `go run cmd/hkcam/main.go -h264_encoder h264_v4l2m2m`

Where do I have to use it? Sorry for my stupid question. :)

**Comment by sighmon** [comment]
@Loremwriter It depends on how you're starting it... but assuming you've used the Ansible playbook to install it you could edit the file `/etc/sv/hkcam/run` following these instructions: https://github.com/brutella/hkcam#advanced-configuration

So the file might look like:

```bash
#!/bin/sh -e
exec 2>&1
v4l2-ctl --set-fmt-video=width=1280,height=720,pixelformat=YU12
exec hkcam --data_dir=/var/lib/hkcam/data --verbose=true --h264_encoder=h264_v4l2m2m
```

**Comment by brutella** [comment]
Hi, sorry for not responding sooner.
I've just release version 0.1.0, which is easy to install on a Raspberry Pi running Raspberry Pi OS (Bullseye).
See the instructions in the readme.
