### ISSUE TITLE
No way to contact Repo Owner?

### ISSUE THREAD

**Issue by earlthesquirrel** [brutella/hkcam#124]
Hello,

I'm trying to contact you to ask questions about the repo and about the software.  Twitter link doesn't allow messaging. (I did Tweet with a mention). No other mechanisms are available that I can find, so am opening an issue.

I'm trying to find out if there is a way from the Raspberry Pi install to update using some of the other instructions.  And/or if there will be a more updated Ing coming out.  I've found some options (such as -pin ) aren't in the version in the Raspberry pi image.  And the ansible config mentioned doesn't seem to be present either.

**Comment by brutella** [comment]
Hi, sorry for not responding sooner.
I've just release version 0.1.0, which is easy to install on a Raspberry Pi running Raspberry Pi OS.
Detailed instructions are available in the readme.
