### ISSUE TITLE
v0.0.7 doesn't fix the no response

### ISSUE THREAD

**Issue by baseship** [brutella/hkcam#15]
After i make the compilation new at the closed issue, the camera worked around for 2 hours.
But now there's no connection recevied, then i downloaded the new Version of HKCam 0.0.7 and flash it with etcher, that's the result...
![IMG_1CC7A31B9DFD-1](https://user-images.githubusercontent.com/11758521/58647940-e2d38200-8308-11e9-992a-22aa30f5db2c.jpeg)

**Comment by RaymondMouthaan** [comment]
Did you remove the camera first and re-added it?

**Comment by brutella** [comment]
Sorry that v0.0.7 doesn't fully resolve this issue.
I think this issue only happens when the iOS devices connects with an IPv6 address.
Still investigating…

**Comment by brutella** [comment]
Fingers crossed that 488f2c7 fixes this issue.

Would be great if somebody could verify that by compiling and updating the hkcam binary.
https://github.com/brutella/hkcam/wiki/How-To-Update#update-from-source

**Comment by RaymondMouthaan** [comment]
@brutella, I will... However I am running 0.0.7 from this morning and until now it still works. Any idea how to reproduce the issue faster?

**Comment by brutella** [comment]
@RaymondMouthaan This issue only seems to affects incoming IPv6 connections. Maybe you can reproduce the issue when you are on an IPv6 only WiFi network.

**Comment by RaymondMouthaan** [comment]
> @RaymondMouthaan This issue only seems to affects incoming IPv6 connections. Maybe you can reproduce the issue when you are on an IPv6 only WiFi network.

as far as I know I don't have an IPv6 network, so I guess we have to be patience until it occurs or even better if it will not :-)

**Comment by RaymondMouthaan** [comment]
@brutella, just build, installed and started [488f2c7](https://github.com/brutella/hkcam/commit/488f2c7a67378511af1de1ffba297f4143b5b5a4), fingers crossed it works 👍

**Comment by dfbills** [comment]
I'm on a IPv6 network and cannot connect after updating to 0.0.7 on both Mac and PI.

**Comment by brutella** [comment]
@dfbills Could you please try the above mentioned fix?

**Comment by brutella** [comment]
Please everybody update to 3a825f0

**Comment by dfbills** [comment]
I'm running 3a825f0, but still don't see any devices from HomeKit.

**Comment by brutella** [comment]
You don't have to add the camera again to HomeKit if you just replaced the binary.

If you want that the camera appears as a new device, you have to delete the contents of the folder `/var/lib/hkcam/data`.

**Comment by dfbills** [comment]
@brutella - Thanks!  For those following this thread, on the Mac, this is the data contents of the "Camera" folder at the root level of the hkcam project.

I finally have both Mac and Pi versions up and streaming again.

<img width="929" alt="Screenshot 2019-06-01 15 07 36" src="https://user-images.githubusercontent.com/238797/58752575-1c2dfe00-847f-11e9-9721-449af2d74b68.png">

**Comment by brutella** [comment]
Does it work now for everybody with the changes in 3a825f0?

**Comment by RaymondMouthaan** [comment]
@brutella, running [3a825f0](https://github.com/brutella/hkcam/commit/3a825f00147702cd4b8da87a19caab6cb2a43696) for two days now and it works!

**Comment by baseship** [comment]
The changes now work. Thanks. Is the Raspian Image also fixed?

**Comment by brutella** [comment]
@baseship v0.0.8, which includes the fix, will be released tomorrow.

**Comment by brutella** [comment]
Should be fixed in [v0.0.8](https://github.com/brutella/hkcam/releases/tag/v0.0.8)
