### ISSUE TITLE
Best update method?

### ISSUE THREAD

**Issue by dfbills** [brutella/hkcam#16]
I'm wondering what the best update method is going to be for this project.  Thinking about installing git on each camera so I can periodically pull down updates or perhaps schedule them with cron.  

@brutella - any thoughts on how one might update say 10 cameras?

**Comment by brutella** [comment]
I see two ways to do that.
1. **update manually via HomeKit** – I don't know how we can tell HomeKit that a new version is available. Other HomeKit accessories can do that, so there should be a way.
or
2. **update automatically** – We could setup a service which periodically checks the Github project for new versions.

Currently you have to manually update as described in the [wiki](https://github.com/brutella/hkcam/wiki/How-To-Update).

**Comment by iMartzen** [comment]
I'm currently working on an [Ansible script](https://github.com/iMartzen/hkcam-update-playbook) for updating the devices. @dfbills, you can use the master-branch if you want to. In the instructions what you need to know.

I also started on a second branch with bash scripting. Probably I want to use this script as a cron job. @brutella, are you planning to build an version check? I already tried it (never code in Go before) and it was working. See attachment for my adjustments -> [main.go.txt](https://github.com/brutella/hkcam/files/3242795/main.go.txt)

@brutella I think your project is awesome 🥇

**Comment by iMartzen** [comment]
Update: I've made a pull request for my adjustments for the possibility to update via automatically cronjob. See [Pull Request #24](https://github.com/brutella/hkcam/pull/24)

**Comment by brutella** [comment]
The recent version [0.2.0](https://github.com/brutella/hkcam/releases/tag/0.2.0) includes a web ui, which lets you install updates.
