### ISSUE TITLE
Automation - motion detected & take snapshot is missing in Home 3

### ISSUE THREAD

**Issue by benbeton** [brutella/hkcam#17]
I'll tried to add the automation in **Home 3** like displayed in your screenshot 

![automation](https://user-images.githubusercontent.com/1405209/58706467-71500e00-83b2-11e9-8efa-edd06f745141.jpg)

but both of the options a missing in the app.
I'm using iPhone XR with iOS 12.3.1 - rPi Zero W  (hkcam 0.7)

is there anything I missed? from the docs  I read, it should work with Home 3

**Comment by brutella** [comment]
As stated on the website that you can use the camera snapshots feature in combination with other HomeKit accessories. In the example a separate HomeKit motion sensors is used to trigger the automation.

**Comment by benbeton** [comment]
got it. ty!

**Comment by glumb** [comment]
Would be nice if we can use the camera itself for the motion detection
