### ISSUE TITLE
Enclosure source files

### ISSUE THREAD

**Issue by daprice** [brutella/hkcam#18]
Would you be able/willing to provide CAD source files for the enclosure? It would be nice to be able to customize the enclosure (for example, I was thinking of trying to add an IR illuminator for night vision) but STLs aren’t great for editing.

**Comment by Vulpecula-nl** [comment]
Me likes them too. I want to add a button for a doorbell. Thanks in advance

**Comment by brutella** [comment]
What file format do you need?
I'm using [Shapr 3D](https://www.shapr3d.com) which exports in XT, STEP, IGES, OBJ, STL and SHAPR.

**Comment by daprice** [comment]
I’d prefer STEP so I can use other CAD software, but I think that also providing the SHAPR files might be good since (as far as I know) STEP files never contain as much editable detail about the model as the original source files do, and other Shapr users might want to make use of that.

Thanks!

**Comment by brutella** [comment]
Done
