### ISSUE TITLE
Selected framerate (30.000000) is not supported by the device

### ISSUE THREAD

**Issue by michaeljanich** [brutella/hkcam#21]
I'm trying it today on Mac - all software was updated just now. Beta OS 10.14.6.

It lists the possible frame rates after including this one:
[avfoundation @ 0x7fd53e800000]   1280x720@[29.970000 29.970000]fps

Pretty close. Any ideas?

THANKS

     -M

DEBUG 2019/06/01 22:17:08 resource.go:43: 192.168.178.25:62321 POST /resource
ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple LLVM version 10.0.1 (clang-1001.0.46.4)
  configuration: --prefix=/opt/local --enable-swscale --enable-avfilter --enable-avresample --enable-libmp3lame --enable-libvorbis --enable-libopus --enable-librsvg --enable-libtheora --enable-libopenjpeg --enable-libmodplug --enable-libvpx --enable-libsoxr --enable-libspeex --enable-libass --enable-libbluray --enable-lzma --enable-gnutls --enable-fontconfig --enable-libfreetype --enable-libfribidi --disable-libjack --disable-libopencore-amrnb --disable-libopencore-amrwb --disable-libxcb --disable-libxcb-shm --disable-libxcb-xfixes --disable-indev=jack --enable-opencl --disable-outdev=xv --enable-audiotoolbox --enable-videotoolbox --enable-sdl2 --disable-securetransport --mandir=/opt/local/share/man --enable-shared --enable-pthreads --cc=/usr/bin/clang --arch=x86_64 --enable-x86asm --enable-libx265 --enable-gpl --enable-postproc --enable-libx264 --enable-libxvid --enable-nonfree --enable-libfdk-aac
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
[avfoundation @ 0x7fd53e800000] Selected framerate (30.000000) is not supported by the device

**Comment by MRvH88** [comment]
Had the same issue, where the stream would not start because of this message. Got it working by changing some things, see #10

**Comment by brutella** [comment]
Should be fixed in [0.1.0](https://github.com/brutella/hkcam/releases/tag/v0.1.0).
