### ISSUE TITLE
Rotating camera image

### ISSUE THREAD

**Issue by G60GT** [brutella/hkcam#22]
I'd love to have the ability to rotate the camera image by 180° (90° and 270° might also be useful under certain circumstances).
It doesn't have to be a UI option (if that's possible at all), some kind of parameter in a config file would suffice.

Background: my rPi has to be mounted upside down for cabling reasons.

**Comment by looxonline** [comment]
+1 to this. I need to mount mine upside down too.

**Comment by pieter** [comment]
You can rotate the image by running this on startup:

`v4l2-ctl --set-ctrl=rotate=180`

**Comment by G60GT** [comment]
Where would I put that to be executed on startup?

**Comment by brutella** [comment]
Put it into the `/etc/sv/hkcam/run` script just before `hkcam` binary is executed.

```shell
#!/bin/sh -e
exec 2>&1
v4l2-ctl --set-ctrl=rotate=180
exec hkcam --data_dir=/var/lib/hkcam/data --verbose=true
```

**Comment by looxonline** [comment]
Legend! Thanks.

**Comment by G60GT** [comment]
Works like a charm. Thank you very much!

Just for the record: I guess, 90 and 270 would work also? Maybe every value between 1 and 359?

**Comment by brutella** [comment]
I've only tried a value of 90 and 180, but I guess 270 will also work.
45 didn't work for me though.

**Comment by G60GT** [comment]
Wouldn't be very efficient anyway, putting a rectangle (video image) inside another rectangle (viewport) in angles different from n*90° …
