### ISSUE TITLE
[Solved] Ansible issue

### ISSUE THREAD

**Issue by AndreaCCIE** [brutella/hkcam#26]
When I try to run the playbook on my Rasp3B, I get this error:

pi@raspicam:~/hkcam/ansible $ ansible-playbook rpi.yml -i hosts --ask-pass
SSH password:
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/pi/hkcam/ansible/roles/hkcam/tasks/configure.yml': line 41, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Reboot
  ^ here

**Comment by brutella** [comment]
Please try again with the changes of 4444343

**Comment by AndreaCCIE** [comment]
Same error :-(

**Comment by AndreaCCIE** [comment]
Got the problem: I was running the playbook from the Raspberry itself.
If done from the Mac, it works fine.

**Comment by serbasan** [comment]
Same error with version 9.11 on raspberry 3b + Any ideas? The add + solution does not work. Thank you
