### ISSUE TITLE
UI corners of Snapshot

### ISSUE THREAD

**Issue by mgoeller** [brutella/hkcam#39]
The Snapshot should be cut to the correct resolution (according to Apple HomeKit certifications) so the corners are round (see left camera) and not edged (right camera). Actually this should be done with ffmpeg and resizing the video as well, because after opening and closing the live stream it will take the last image of the live stream as snapshot which is in this case "too big as well" and shows edged. This takes however a lot of resources, probably not very suitable for the Raspberry Pi Zero.
![Screenshot 2019-06-24 at 13 01 23](https://user-images.githubusercontent.com/40425388/60014270-dda3f180-9680-11e9-9800-22ab719f958a.png)

**Comment by brutella** [comment]
The masking of the corners is done the Home app.
There is no indication of rounded corners in the HAP specification.

**Comment by mgoeller** [comment]
Correct, but the Home App is only masking the corners if the scale of the snapshot if the ratio is correct. The current 480x360 resolution of the snapshots is not officially accepted and results therefore in the UI error with the edged corners. The correct screenshots are produced when I edit the ffmpeg command to "-scale=1280:720".
![IMG_0871](https://user-images.githubusercontent.com/40425388/60029402-60d53f80-96a1-11e9-8b81-bae8bacdc09a.png)
![IMG_0870](https://user-images.githubusercontent.com/40425388/60029403-60d53f80-96a1-11e9-9555-7a1f9e1bb00e.png)
![snapshot_2019-06-24T15:50:59+01:00](https://user-images.githubusercontent.com/40425388/60029404-616dd600-96a1-11e9-91e3-d0feee04bd84.jpeg)
![snapshot_2019-06-24T15:37:09+01:00](https://user-images.githubusercontent.com/40425388/60029406-616dd600-96a1-11e9-9a65-f471957f9db0.jpeg)
