### ISSUE TITLE
Multiple Camera's

### ISSUE THREAD

**Issue by ericklil** [brutella/hkcam#41]
Great Work Matthias !!

Thank you for your continued iterations of `HomeKit` bettering products
Can you indicate how to run multiple camera's 
Presumably one must change the `MAC address` and perhaps the `001-02-003` code?

PS setting up wifi  requires setting the country in the `wpa_supplicant.conf`

The below worked for me:

country=US
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
    ssid="your_real_wifi_ssid"
    scan_ssid=1
    psk="your_real_password"
    key_mgmt=WPA-PSK
}

**Comment by brutella** [comment]
> Can you indicate how to run multiple camera's
> Presumably one must change the MAC address and perhaps the 001-02-003 code?

Actually you don't have to change anything to get multiple cameras to work.
The PIN code can stay the same because it's only used for the initial pairing. 

But I would change the hostnames of your Raspberry Pis, so that you can distinguish them.
I personally use the following hostnames for my cameras: `hkcam01`, `hkcam02`, and so on.

> PS setting up wifi requires setting the country in the wpa_supplicant.conf

Oh, that's new to me. Is it really a requirement?

**Comment by ericklil** [comment]
Thanks.

> Oh, that's new to me. Is it really a requirement?

> 

I believe the default country for WiFi on `RPI's` is`GB` and as such perhaps carries the same channels as `DE`.
As the WiFi did not seem to connect I put a head on the `RPi Zero` and saw a line upon start up "Wifi does not start without country being set" or something to that extend. 
After adding the country code if worked fine.

**Comment by libewa** [comment]
> > PS setting up wifi requires setting the country in the wpa_supplicant.conf 
> 
> Oh, that's new to me. Is it really a requirement?

You can use `sudo raspi-config` or - if available - the UI too. And I think, there's a lot of bash scripts in the web.

**Comment by brutella** [comment]
Closed due to inactivity.
