### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by AchimPieters** [brutella/hkcam#42]
May I do a suggestion for future development?
Have a look at this: https://www.ring.com :door: :bell:
This is not my field of expertise but I'm sure @brutella or some other smart person here could mange to make this happen? :relaxed:

Best regards!

**Comment by brutella** [comment]
What features do you want to see in hkcam related to ring?

**Comment by timoschilling** [comment]
I think he mean that there could be a hkring based on hkcam.

**Comment by AchimPieters** [comment]
@brutella Thank you for your quick reply !

Well what I really would like to see is the HKcam as a doorbell like the Ring only without the subscription!

- A button ( offcourse :blush: ) for a Chime eg.
- two-way talk
- motion-activated 
- Receive real-time notifications

**Comment by phenomeus** [comment]
I would like to see that also in action :) I have to run pretty fast to get my delivery guy so a two way talk by phone or watch would be awesome.

**Comment by Mosher23** [comment]
make this happen please

**Comment by brutella** [comment]
There are currently no plans to make a doorbell out of hkcam.
