### ISSUE TITLE
How to install on Rasbian Buster?

### ISSUE THREAD

**Issue by La-te** [brutella/hkcam#43]
Is all working with freshly released Rasbian Buster? Which is the preferred way for fresh install and which are known to work? hkcam image and apt upgrade, official Rasbian Buster and hkcam ansible or official Rasbian Buster and manual installation?

**Comment by brutella** [comment]
I haven't tested it on Buster yet.

**Comment by robacarp** [comment]
@La-te I went through a manual install on Stretch, and [my notes are here](https://robacarp.com/2019/06/09/hkcam_manual_installation.html). I'm sure it's not _identical_ but the installation is straightforward enough that, as long as the packages exist for Buster, I doubt it'll cause any problems.

**Comment by MadAEng** [comment]
> @La-te I went through a manual install on Stretch, and [my notes are here](https://robacarp.com/2019/06/09/hkcam_manual_installation.html). I'm sure it's not _identical_ but the installation is straightforward enough that, as long as the packages exist for Buster, I doubt it'll cause any problems.

Attempting to install it on Buster according to your notes, it won't install `v4l2loopback`, tried a workaround by installing it in a different way, but then I get the `modprobe: FATAL: Module v4l2loopback not found in directory /lib/modules/4.xxxxx` error.

I'm too much of a n00b to figure this out on my own, any clues on what I could do to get it working?

**Comment by rcarmo** [comment]
See #90 for the changes I did.

**Comment by PvdGulik** [comment]
**Running on Raspberry Pi Zero W, with Buster!!**

Hereby my detailed instructions:

_Bases on Robert Carpenter's [installation](https://robacarp.com/2019/06/09/hkcam_manual_installation.html) with a few changes/additions:_

**1 Preparations:**
-  Flash SD card with image Raspberry Buster Lite using Raspberry Pi Imager app or equivalent.
- add the files ssh & wpa_supplicant.conf (with your Wifi-settings) in the root of the card
- Put SD in Raspberry-Pi Zero W, and powerup your Raspberry Pi
- find ip-address and connect with `ssh pi@ip-address`
- The password is: raspberry

**2 Change basic settings:**
- `sudo Raspi-config`
- Change password, hostname, GPU —>128 Mb,  Timezone, Wifi regional settings, expand file-system), reboot
- connect with `ssh pi@ip-address-of-your-pi`
- the password is now your created password
- `sudo apt update -y && sudo apt full-upgrade -y`
- `sudo reboot`

**3 Before you go any further sure your camera is working! If not resolve this first:**
- connect with `ssh pi@ip-address`
- the password is again your created password
- test for Raspberry Pi camera module: 
- `raspistill -o test.jpg`
- test for usb-camera:
- `sudo apt install fswebcam`
- `fswebcam test.jpg`
You might need to add the “dwc_otg.fiq_fix_enable” in /boot/cmdline.txt
> - `sudo nano /boot/cmdline.txt`
> - add `dwc_otg.fiq_fix_enable`, followed by <ctrl-x>, <y>, <Enter>

**4 If camera is working, than install following:**
- `sudo apt install raspberrypi-kernel-headers`
- `sudo apt install v4l2loopback-dkms`
- `sudo apt install ffmpeg`
Know you need to know on which device your camera is connected. When using r`aspistill -o test.jpg` or `fswebcam test.jpg`, you'll see something like "--- Opening /dev/video**0**..". The number after video, here "**0**" you'll need in the following "...video_nr=**0**...":
- `echo 'options v4l2loopback video_nr=0’ | sudo tee -a /etc/modprobe.d/v4l2loopback.conf`
- `sudo modprobe v4l2loopback`
- `echo v4l2loopback | sudo tee -a /etc/modules`
- `sudo modprobe bcm2835-v4l2`
- `echo bcm2835-v4l2 | sudo tee -a /etc/modules`
- `sudo reboot`
- connect with `ssh pi@ip-address`
- the password is again your created password
- Check if v4l2loopback is correct installed by:
- `v4l2-ctl --list-devices`
- If all correct you'll find detailed info about the virtual video device
- Check if ffmpeg is working one:
- `ffmpeg -f v4l2 -i /dev/video0 -codec:v copy -f v4l2 /dev/video1`.
For old camera's you might need ` LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libv4l/v4l1compat.so ffmpeg -f v4l2 -i /dev/video0 -codec:v copy -f v4l2 /dev/video1`

**5 Install HKCam**
- `wget https://github.com/brutella/hkcam/releases/download/v0.0.9/hkcam-v0.0.9_linux_armhf.tar.gz`
- `tar xzf hkcam-v0.0.9_linux_armhf.tar.gz`
- `cd hkcam-v0.0.9_linux_armhf`
- `sudo cp usr/bin/hkcam /usr/local/bin`
- `cd /`
- `sudo adduser --system --ingroup video hkcam`
- `sudo usermod -a -G video hkcam`

**6 Edit/add _Systemd Service Configuration_ and _Run Script_**
Systemd Service Configuration:
`$ sudo nano /etc/systemd/system/hkcam.service`
add:

```
# /etc/systemd/system/hkcam.service

[Unit]
Description=HKcam HomeKit Camera
After=syslog.target network-online.target

[Service]
Type=simple
User=hkcam
WorkingDirectory=/home/hkcam
ExecStart=/usr/local/bin/hkcam
Restart=always
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target
```, followed by <ctrl-x>, <y>, <Enter>

Run Script:
`sudo nano /etc/hkcam`
add:

```
#!/bin/bash
# /etc/hkcam

# set the video4linux ctl parameters
v4l2-ctl --set-fmt-video=width=1280,height=720,pixelformat=YU12
v4l2-ctl -c video_bitrate=1000000

# exec over to hkcam
exec /usr/local/bin/hkcam --min_video_bitrate=500
# for old camera’s
exec LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libv4l/v4l1compat.so /usr/local/bin/hkcam --min_video_bitrate=500
```, followed by <ctrl-x>, <y>, <Enter>

**7 Activate the service**
`sudo systemctl daemon-reload`
`sudo systemctl start hkcam`
`sudo systemctl enable hkcam`
`sudo reboot`

Your HKCam should now be working. Connect in the Homekit-app, following the instructions.

**Comment by brutella** [comment]
`hkcam` supports Buster and Raspberry Pi OS since version [0.1.0](https://github.com/brutella/hkcam/releases/tag/0.1.0).
