### ISSUE TITLE
Auto exposure

### ISSUE THREAD

**Issue by runty** [brutella/hkcam#44]
Things look good inside, but if I point the camera out the window everything gets blown out. Is there auto exposure?

**Comment by brutella** [comment]
The camera should automatically set the exposure the next time you start the stream.

**Comment by La-te** [comment]
I was just about to open this issue. The outside photo is unusable due to over exposure. It is almost white only. Then with `raspistill` command I get expected nice photo. These work just fine.

`raspistill -ex auto -o exauto.jpg`
`raspistill -o default.jpg`

**Comment by La-te** [comment]
Actually, the issue affects also darkness. Then hkcam might produce almost black photo while with `raspistill` you get some quite dark photo but still something that can be expected from this kind of camera.

With hkcam both exposure issues can be seen in Apple Home and Home 3 even with snapshots.

**Comment by brutella** [comment]
If I set auto exposure to 0 (automatic mode) via `v4l2-ctl --set-ctrl auto_exposure=0`, the exposure is updated while streaming.

**Comment by La-te** [comment]
It was like that already for me. Setting it again didn't make a difference.
`$ v4l2-ctl --get-ctrl auto_exposure`
`auto_exposure: 0`
`$ v4l2-ctl --set-ctrl auto_exposure=0`
