### ISSUE TITLE
Terrible camera quality on raspberry pi zero

### ISSUE THREAD

**Issue by hindsc52** [brutella/hkcam#46]
I have run through these steps in this issue, but still have pretty terrible video quality.

I am running on v0.0.9

This is running on anew PI Zero with the official 1080p camera module.
![IMG_6359](https://user-images.githubusercontent.com/14273378/60598076-fbb9d200-9da3-11e9-8532-a102996b060e.PNG)

_Originally posted by @hindsc52 in https://github.com/brutella/hkcam/issues/4#issuecomment-508107871_

**Comment by chrismarquardt** [comment]
This doesn't seem to be an issue of the Raspberry or of the software, it looks very much like your camera is out of focus. Does your camera have something in the front that turns on a thread? If yes, turn it while viewing the live stream and see what that does.

**Comment by hindsc52** [comment]
> This doesn't seem to be an issue of the Raspberry or of the software, it looks very much like your camera is out of focus. Does your camera have something in the front that turns on a thread? If yes, turn it while viewing the live stream and see what that does.

It looks like it dos turn on . thread but it seems very difficult. almost like turning it would break the camera :/

**Comment by hindsc52** [comment]
Just ordered a tool from PiHut todo this.

**Comment by hindsc52** [comment]
My run file: 

```
pi@raspberrypi:~ $ cat /etc/sv/hkcam/run
#!/bin/sh -e
exec 2>&1
v4l2-ctl --set-ctrl=rotate=90
v4l2-ctl --set-fmt-video=width=1280,height=720,pixelformat=YU12
v4l2-ctl -c video_bitrate=1000000
exec hkcam --data_dir=/var/lib/hkcam/data --verbose=true
```

**Comment by brutella** [comment]
I currently working on a lens adjustment tool which can be 3D-printed #36

**Comment by hindsc52** [comment]
Gotta buy a 3d printer now ;) although as this is the only item I need to right now its way.... way cheaper to buy the one for Adafruit for me :)
