### ISSUE TITLE
No camera connection via 4G mobil

### ISSUE THREAD

**Issue by bioniccid** [brutella/hkcam#47]
I set up a HKcam with the version 0.0.9 - and it works fine when I am in the same wifi. When I deactivate the wifi and try to activate the camera via 4G both apps (HomeKit and Home 3) quickly show the message: "Keine Antwort - Die Kamera antwortet nicht."

I used the fix with the minimum bitrate to boost image quality, but also when I set the bitrate down to 5 (from 800), still I get the same message... do someone have an idea what the problem is?

Ps.: I change the hostname, because I have another pi in my network...

**Comment by brutella** [comment]
You need a home hub to remotely connect to your HomeKit accessories.
https://support.apple.com/en-us/HT207057

**Comment by bioniccid** [comment]
Sorry  - forgot to mention... I have an iPad as a hub. All other HomeKit accessoires work fine via 4G...

**Comment by RaymondMouthaan** [comment]
Have you tried to remove the cam from the Home app and re-add it after using 00102003?

**Comment by bioniccid** [comment]
That is another little problem ;-) I already re-added the cam many times. Nearly every time I had rebooted it. So yeah... I did ;-)

**Comment by RaymondMouthaan** [comment]
Okay, I am still running v0.0.8 + commit [48e4d](https://github.com/brutella/hkcam/commit/48e4dbc384044d69b78166d0ca9b59dcc76cde63) and have no problems what so ever .. 

Does hkcam work both on your iPad and iPhone when you are connected to WiFi? I have seen that my iPad sometimes is out-of-sync compared to my iPhone (not only for HKCam but for other accessory too). Solution I use is, simple reboot the iPad (Home Hub) and it get's synced again.

**Comment by bioniccid** [comment]
Thanx for the tip... it looks like rebooting the iPad worked. Even the iPad worked fine with the cam before rebooting. Maybe a reboot has to be done after adding the cam via the iPhone...

I'm pretty new to this... what does "commit 48e4d" mean and how do I apply it?

**Comment by RaymondMouthaan** [comment]
Nice to read that it worked out for you :-) 

Forget about commit 48e4d, this commit is included in v0.0.9 which you are running already :)

**Comment by bioniccid** [comment]
Thats true - but I think there will be a next "commit"... ;-) And then I would like to know what to do... Is a commit a patch?

**Comment by RaymondMouthaan** [comment]
A commit is a change to GitHub and could be indeed a patch or a new feature ... How to update from source can be found [here](https://github.com/brutella/hkcam/wiki/How-To-Update#update-from-source)
