### ISSUE TITLE
Unable to access over internet

### ISSUE THREAD

**Issue by vassilmladenov** [brutella/hkcam#49]
I have a Raspberry Pi 2 B with 256MB allocated for video memory. I ran the Ansible playbook from master today (6a81223), and I have a flawless stream on my home router. Over LTE, however, I get "No Response". This also happens on the guest network of my router. Does `hkcam` support streaming over the internet? How can I debug this?

**Comment by timoschilling** [comment]
Does you have an AppleTV or iPad configured as Home Hub?

**Comment by timoschilling** [comment]
`hkcam` doesn't direct support controlling / streaming over the internet, that's part of Apples HomeKit System which needs an Home Hub to work remotely.
https://support.apple.com/en-us/HT207057

**Comment by vassilmladenov** [comment]
@timoschilling I do have an Apple TV 4 configured as a Home Hub. My controlling my lights works over LTE with a bit of delay, but the camera doesn't launch. My guess is that the Apple TV isn't communicating with the Pi, but I'm not sure how to start debugging.

**Comment by AndreaCCIE** [comment]
I have the same issue, on one of 2 cams.
Let's put this is a context: 
- 1 pi zero w
- 1 pi 3 B
Both running the same code (0.0.9) and Raspbian version, same configuration settings.
The issue is when I disconnect the phone from WiFi, only the 3 B shows a steaming, see attached animated gif

![ezgif com-video-to-gif-3](https://user-images.githubusercontent.com/48698293/61185240-e881ee80-a64e-11e9-8f1a-068d36a08c54.gif)

**Comment by brutella** [comment]
Does it work if you change the hostnames to be different for the RPis?

**Comment by AndreaCCIE** [comment]
None of them have the same host name, what I noticed is that this problem doesn't always shows up.
This morning is working as expected, not sure if it's related to apple or hkcam.

**Comment by libewa** [comment]
Does your router have a VPN? You can try to connect your phone over it, then, for the RPi it looks like your home (and for websites, VoIP etc. too).

**Comment by brutella** [comment]
Please try the latest version [0.1.0](https://github.com/brutella/hkcam/releases/tag/v0.1.0) which should be more stable.
