### ISSUE TITLE
IR light ???

### ISSUE THREAD

**Issue by fisch55** [brutella/hkcam#50]
Is there a possibility to connect IR LIGHT for nightview?

**Comment by brutella** [comment]
Yes this is possible.
But there is currently no space reserved for IR lights in the provided enclosure.

**Comment by AndreaCCIE** [comment]
You can use something like this and glue it, just need to find out how to power it:

![](http://cdn.instructables.com/FP4/6KRU/HU8O8WP2/FP46KRUHU8O8WP2.MEDIUM.jpg)

**Comment by libewa** [comment]
> You can use something like this and glue it, just need to find out how to power it:
> 
> ![](http://cdn.instructables.com/FP4/6KRU/HU8O8WP2/FP46KRUHU8O8WP2.MEDIUM.jpg)

You can plug it into USB, but then you have to change the source code, or ist there any flag (for example `--ir-light`?), @brutella ?

**Comment by libewa** [comment]
Or it uses a second power supply,but then you probably need a wall socket adapter...

**Comment by brutella** [comment]
I would recommend using the [ELP 1080P USB camera](https://de.aliexpress.com/item/4000562253329.html), which has a waterproof enclosure and includes IR LEDs for night vision.
