### ISSUE TITLE
runsvdir issue at boot

### ISSUE THREAD

**Issue by AndreaCCIE** [brutella/hkcam#51]
When I boot any of the cameras (regardless it's a zero or 3), I get this error and the steaming doesn't work:

pi@zerocam:~ ps aux | grep hkcam
root      1516  0.0  0.2   1864   972 ?        Ss   17:03   0:00 runsvdir -P /etc/service log:  unable to lock supervise/lock: temporary failure runsv hkcam: fatal: unable to lock supervise/lock: temporary failure runsv hkcam: fatal: unable to lock supervise/lock: temporary failure runsv hkcam: fatal: unable to lock supervise/lock: temporary failure runsv hkcam: fatal: unable to lock supervise/lock: temporary failure runsv hkcam: fatal: unable to lock supervise/lock: temporary failure

If I kill the process, it starts again and everything gets fixed.

I'm using 0.0.9

**Comment by brutella** [comment]
Does this happen after every reboot?

**Comment by AndreaCCIE** [comment]
Yes, it does

**Comment by AndreaCCIE** [comment]
Anyone else is having this issue? I have to kill the processes every each reboot (or possibly power outage)

**Comment by brutella** [comment]
There might be an issue with runit on Buster.

**Comment by AndreaCCIE** [comment]
It could be. Since buster is now the golden release, is there anything I can do to help you in troubleshooting this?

**Comment by brutella** [comment]
With the release of [0.1.0](https://github.com/brutella/hkcam/releases/tag/v0.1.0), I've updated the installation instructions in the readme to work with Raspberry Pi OS. The ansible script now also works for Raspberry Pi OS.

**Comment by northben** [comment]
I'm having the same issue today, I've tried both Raspberry Pi OS legacy (buster) and the current bullseye release. I'm using the ansible deployment.
