### ISSUE TITLE
rebuild with Raspbian buster images (currently using stretch)

### ISSUE THREAD

**Issue by pleasantone** [brutella/hkcam#52]
Due to obsolete and incompatible v4l2loopback drivers, and general security issues, I'd like to put a request in, for your, as well as everyone else's sanity, that we move up to Raspbian buster for the official distribution.

**Comment by rcarmo** [comment]
See #90 for the changes I did.

**Comment by PvdGulik** [comment]
Hello brutella,

I would like to see a buster image, is this still in progress? Would be nice!

Thanks!

**Comment by PvdGulik** [comment]
I got it working on Buster, following this link https://robacarp.com/2019/06/09/hkcam_manual_installation.html
Only same problem for me as with the stretch image, I have to start ffmpeg with a command in SSH...

**Comment by PvdGulik** [comment]
I got it working, see [here](https://github.com/brutella/hkcam/issues/43#issuecomment-869168674) the detailed installation.

**Comment by brutella** [comment]
I've just released version [0.1.0](https://github.com/brutella/hkcam/releases/tag/v0.1.0) and updated the instructions in the readme for Raspberry Pi OS. Installing v4l2loopack and ffmpeg is easy now.
