### ISSUE TITLE
100% cpu usage on pi zero w

### ISSUE THREAD

**Issue by mentaluproar** [brutella/hkcam#54]
Is there a way to test that this is using hardware encoding?  When active, it takes full CPU, and takes a long time to show anything on the iphone/mac/etc.

**Comment by brutella** [comment]
I've just released version [0.1.0](https://github.com/brutella/hkcam/releases/tag/v0.1.0), which should run much more stable now. The instructions in the readme and the ansible script work for Raspberry Pi OS.
