### ISSUE TITLE
Error when using the pre-configured Raspbian image

### ISSUE THREAD

**Issue by remko2000** [brutella/hkcam#55]
After copying the pre-configured Raspbian image on my SD-card and putting it in my raspberry zero (and set the ssid) and add the camera to homekit I get the following errors (sudo hkcam) in the commandline:

`[video4linux2,v4l2 @ 0xfa32f0] ioctl(VIDIOC_G_FMT): Invalid argument
/dev/video1: Invalid argument
[video4linux2,v4l2 @ 0x864180] Cannot open video device /dev/video0: 
No such file or directory
/dev/video0: No such file or directory
[video4linux2,v4l2 @ 0xd1c1e0] ioctl(VIDIOC_G_FMT): Invalid argument
/dev/video1: Invalid argument`

What did I wrong?

**Comment by AndreaCCIE** [comment]
Are you sure the camera is correctly installed? Try “raspistill -o test.jpg” from the command line. If you get an error, it could be the camera/cable/board.

**Comment by remko2000** [comment]
Hai Andrea,
Thx for your reply. I really appreciate it.
Indeed I get an error. A connector was loose :-(
It works now in homekit but…….
it seems a bit unreliable. Sometimes I get a picture in homekit but often it falls away again. Or I get the message that someone else is looking at the camera while that is not the case. Sometimes the only solution is to reset the raspberry zero.
If I typ in the command line hkcam now I get only:

DEBUG 2019/08/02 10:19:45 camera_control.go:194: {"assets":[]}
INFO 2019/08/02 10:19:45 ip_transport.go:186: Listening on port 43839


Are there any options that can get more stable?

Regards Remko

**Comment by AndreaCCIE** [comment]
I have the same issue, but I don't know if it's HKCAM of Homekit. I'll try a different solution over the week end and update Matthias about this.
Please note that this software has not been officialy tested with Buster (that I'm using) yet

**Comment by remko2000** [comment]
or right thanx. Can you update me about your testcase? I’m very curious. I use the preconfigured image and not buster but if it works better with buster I use buster.



Op 2 aug. 2019, om 11:48 heeft Andrea <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I have the same issue, but I don't know if it's HKCAM of Homekit. I'll try a different solution over the week end and update Matthias about this.
Please note that this software has not been officialy tested with Buster (that I'm using) yet

**Comment by PvdGulik** [comment]
Hello, did one of you (@remko2000 of @AndreaCCIE) this solved?
I'm still looking at this problem now for days, but can't find the solution.

Thanks!

**Comment by AndreaCCIE** [comment]
I stopped using this software one year ago as it’s not developed anymore. It was a good idea though.

**Comment by brutella** [comment]
I've just released version [0.1.0](https://github.com/brutella/hkcam/releases/tag/v0.1.0), which should run much more stable now.
