### ISSUE TITLE
Universal case

### ISSUE THREAD

**Issue by svh1985** [brutella/hkcam#57]
Would it be possible for you to create a case where a RPi Zero W with headers fits?
I think a RPi without headers should then also fit in that case. I think that would result in a universal case :)

**Comment by brutella** [comment]
There are no plans for a printable case for the RPi Zero W. I'm now using a USB camera. For example the [ELP 1080P camera](https://de.aliexpress.com/item/4000562253329.html) can be easily mounted, is waterproof and supports night vision with IR LEDs out of the box. I find that more reliable than a standard camera module in a 3D printed enclosure.
