### ISSUE TITLE
Kernel upgrade broke something

### ISSUE THREAD

**Issue by AndreaCCIE** [brutella/hkcam#59]
Hi, after a kernel upgrade (4.19.66) I noticed errors related to /dev/video1 and the cameras did stop responding in HomeKit. I had to reinstall the software through ansible to have the all up and running again.
Is this the expected behaviour?

**Comment by SimplyGardner** [comment]
Just updated my Pi and it broke as well. Going to have to do a fresh install and avoid updating.

**Comment by alexsalex** [comment]
The same with me. After upgrade the device /dev/video0 just disappear.

**Comment by brutella** [comment]
The project doesn't work with the latest kernel. This is a known issue.

**Comment by AndreaCCIE** [comment]
If it’s a known issue, it should be written Somewhere here
