### ISSUE TITLE
Two cameras in the same network does not work

### ISSUE THREAD

**Issue by Tymo3** [brutella/hkcam#64]
Hi
First of all - thank you for this project - it is really great!
Does anybody tested two cameras in the same network?

First camera installed. And is working.
Second camera installed. Can be added to home app. But after adding second camera stopped working. I am wondering if it is connected to same PIN (00102003)? or same hostname? 

Any other thoughts?
T

**Comment by AndreaCCIE** [comment]
I’ve got 5 cameras working in my hone without any problem. Just be sure the dns name is unique for each camera

**Comment by Tymo3** [comment]
Andrea. It works! Thnx 
T
