### ISSUE TITLE
Feature Request / Question: Grab stills from Homebridge Camera

### ISSUE THREAD

**Issue by ctschach** [brutella/hkcam#67]
I know it's a bit off-topic and basically the oposite of hkcam, but as the "guru of HomeKit" this might be the right person to ask.

I'm basically looking for a way to access the videostream and/or snapshots from a HomeKit camera from the command line (e.g. via a Raspberry). Based on external events I would like to grab and save an image of the camera to my local storage.

Are you aware of any tools that can do this? Is there any kind of documentation how to access HomeKit from a program, authenticate and access the accessories?

Thanks...Danke...Carsten

**Comment by brutella** [comment]
Please ask questions about Homebridge on their Github page.

Re: Grabbing stills: hkcam automatically stores images to a temporary file, before sending it to the connected HomeKit client. Accessing a HomeKit camera from the command-line though is only possible if you are able to pair with the camera. This might be tricky.
