### ISSUE TITLE
Ports?

### ISSUE THREAD

**Issue by RefineryX** [brutella/hkcam#70]
I have all my IOT devices isolated to one VLAN.
Wondering which ports HKCAM uses so I can open these on my router to allow me to gain access from VLAN 1.

Thanks.

**Comment by brutella** [comment]
The project currently uses a random port which is assigned by the OS.
Would you be interested in a feature which lets you specify the port?

**Comment by RefineryX** [comment]
For sure. That would be super helpful.

**Comment by brutella** [comment]
See #85
