### ISSUE TITLE
Removed Accessory and can't add back

### ISSUE THREAD

**Issue by hquinones** [brutella/hkcam#72]
I removed the accessory in error and can't add the camera back.  Its no longer found by HomeKit app through add new accessory.  Any advise?

**Comment by brutella** [comment]
If HomeKit didn't properly unpair with hkcam, you have to manually remove the stored data on the Raspberry Pi.

```
ssh pi@raspberrypi.local
rm -rf /var/lib/hkcam/data
```

Then restart the daemon and hkcam should be available to HomeKit as a new accessory.

```
sv restart hkcamd
```
