### ISSUE TITLE
Resetting the HK credentials

### ISSUE THREAD

**Issue by ericklil** [brutella/hkcam#73]
This is great work, Thank you!

I can't seem to find how to reset the HK configuration. This accessory ir removed from my HomeKit eco system while it was not running, and presumably the configuration was not reset. Can this be done via SSH or suck

I'd be grateful for some information on this.

**Comment by brutella** [comment]
You will have to delete the folder which contains the persistent data of hkcam.
If you are using the pre-configured Raspbian image, this would be in `/var/lib/hkcam/data`.
Once you have deleted that folder and restarted the RPi, the camera should appear as a new accessory in HomeKit.
