### ISSUE TITLE
Is any support for this project? Or its as is....

### ISSUE THREAD

**Issue by alexsalex** [brutella/hkcam#83]
Subj

**Comment by brutella** [comment]
What issue do you have?

**Comment by alexsalex** [comment]
https://github.com/brutella/hkcam/issues/82
https://github.com/brutella/hkcam/issues/81

Please

**Comment by alexsalex** [comment]
any updates?

**Comment by brutella** [comment]
I've replied to #81 and #82 is a duplicate of #45
