### ISSUE TITLE
It starts slowly and has a low frame rate

### ISSUE THREAD

**Issue by jliu666** [brutella/hkcam#84]
I use my mac book pro for test. It starts slowly and has a low frame rate.

**Comment by brutella** [comment]
I've experienced the same when using it on my MacBook Pro.
This seems strange because this worked much better in previous versions of macOS.

**Comment by jliu666** [comment]
How to resolve it? I try to use FFmpeg golang bindings [goav](https://github.com/giorgisio/goav) to instead of ffmpeg cmd. But it's very complicated, and I wonder if there's a better way.

**Comment by brutella** [comment]
I've just released version [0.1.0](https://github.com/brutella/hkcam/releases/tag/v0.1.0) where I've changed the h264 encoder on macOS from libx264 to h264_videotoolbox. Now it runs perfectly again.
