### ISSUE TITLE
mah@macbook public ssh key in ~/.ssh/authorized_keys of image

### ISSUE THREAD

**Issue by jonathandann** [brutella/hkcam#94]
Looks like the public key for mac@macbook is still there in the `~/.ssh/authorized_keys` of the publicly released image. It should probably be stripped as part of making the image.

Thanks!

**Comment by northben** [comment]
I'm really concerned about this as it would allow the holder of this key to connect to the camera remotely. Has the codebase been compromised?

**Comment by brutella** [comment]
The codebase is not compromised. I've just forgotten to remove the SSH key. #105

**Comment by jonathandann** [comment]
@brutella Thanks!
