### ISSUE TITLE
Failed using Ansible

### ISSUE THREAD

**Issue by stuarteaton** [brutella/hkcam#98]
TASK [Copy /tmp/hkcam-v0.0.9_linux_armhf/usr to /usr] ********************************************************************************************************************************************************************************************************
fatal: [raspberrypi.local]: FAILED! => {"changed": true, "cmd": "cp -rp /tmp/hkcam-v0.0.9_linux_armhf/usr/* /usr", "delta": "0:00:00.020488", "end": "2020-10-29 18:09:01.894338", "msg": "non-zero return code", "rc": 1, "start": "2020-10-29 18:09:01.873850", "stderr": "cp: cannot create regular file '/usr/bin/hkcam': Text file busy", "stderr_lines": ["cp: cannot create regular file '/usr/bin/hkcam': Text file busy"], "stdout": "", "stdout_lines": []}

Installed manually on Raspberry Pi 3.
Got as far as:
ansible-playbook rpi.yml -i hosts --ask-pass  

but always fails with the password even though the Pi has the key.
Ran as:
ansible-playbook rpi.yml -i hosts

and it gets further but fails at the error message above. Any ideas?
Has anyone got this running on anything other than Raspberry Pi Zero?

Thanks

**Comment by ArndtGold** [comment]
Unfortunately I got the same error on a Raspberry Pi Zero W. It apparently does not currently run on a Raspberry Pi Zero W either.

**Comment by brutella** [comment]
> cp: cannot create regular file '/usr/bin/hkcam': Text file busy

This error means that the executable file /usr/bin/hkkcam cannot be overwritten because it is currently executed.
Try to stop the running hkcam process and try again.
